project:
  type: website

website:
  title: "SG Public Dollars"
  navbar:
    left:
    - text: "Project Proposal"
      href: Proposal/proposal.qmd
    - text: "Product"
      href: 
      
    right:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "Team"
      
format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true

editor: visual

