project:
  type: website

website:
  title: "Lets’ Track Public Dollars!"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: Proposal/proposal.qmd
        text: "Proposal"




format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true

editor: visual

