project:
  type: website

website:
  title: "Lets’ Track Public Dollars!"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: Proposal/proposal.qmd
        text: "Proposal"
      - herf: Data_Preprocessing.qmd
        text: "Data Preprocessing"
      - text: "Meetings"
        menu:
        - text: "Meeting 1"
          href: meetings/meeting_notes_1.qmd
        - text: "Meeting 2"
          href: meetings/meeting_notes_2.qmd
        - text: "Meeting 3"
          href: meetings/meeting_notes_3.qmd
        - text: "Meeting 4"
          href: meetings/meeting_notes_4.qmd


format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true

editor: visual

