project:
  type: website

website:
  title: "ISSS608 Team 4 Project Website"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: "Proposal/proposal.qmd"
        text: "Project Proposal"
      
     


format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true

editor: visual

