project:
  type: website

website:
  title: "Lets’ Track Public Dollars!"
  navbar:

    right:
      - href: index.qmd
        text: "Home"
      - href: Proposal/proposal.qmd
        text: "Proposal"
      - text: "Data Preprocessing"
        menu:
        - text: "For LDA"
          href: Data_Preprocessing/Data_Preprocessing_LDA.qmd
        - text: "Network Insights Module"
          href: Data_Preprocessing/Data_Processing_Network.qmd
        - text: "Procurement Trends Module"
          href: Data_Preprocessing/Data_Processing_Temporal.qmd
        
      - text: "Poster"
        href: Poster.qmd
      - text: "Meetings"
        menu:
        - text: "Meeting 1"
          href: meetings/meeting_notes_1.qmd
        - text: "Meeting 2"
          href: meetings/meeting_notes_2.qmd
        - text: "Meeting 3"
          href: meetings/meeting_notes_3.qmd
        - text: "Meeting 4"
          href: meetings/meeting_notes_4.qmd

    left:
      - text: "Shiny App"
        menu:
        - text: "Shiny App"
        
        - text: "User Guide"
       
        


format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true

editor: visual

